{
  parserClass="ris58h.androidkeymaps.intellij.kl.parser.KlParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Kl"
  psiImplClassSuffix="Impl"
  psiPackage="ris58h.androidkeymaps.intellij.kl.psi"
  psiImplPackage="ris58h.androidkeymaps.intellij.kl.psi.impl"

  elementTypeHolderClass="ris58h.androidkeymaps.intellij.kl.psi.KlTypes"
  elementTypeClass="ris58h.androidkeymaps.intellij.kl.psi.KlElementType"
  tokenTypeClass="ris58h.androidkeymaps.intellij.kl.psi.KlTokenType"
}

klFile ::= item_*

private item_ ::= (COMMENT|key_expr|axis_expr)

key_expr ::= KEY_KEYWORD USAGE_KEYWORD? NUMBER IDENTIFIER key_flags
key_flags ::= (IDENTIFIER)*

axis_expr ::= AXIS_KEYWORD NUMBER (IDENTIFIER|axis_split|axis_invert) axis_flat
private axis_split ::= SPLIT_KEYWORD NUMBER IDENTIFIER IDENTIFIER
private axis_invert ::= INVERT_KEYWORD IDENTIFIER
private axis_flat ::= (FLAT_KEYWORD NUMBER?)?
